"""Initial migration - Updated Camera model structure

Revision ID: 563bbcfd5bd0
Revises: 
Create Date: 2025-08-15 14:08:02.439843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563bbcfd5bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('ip_address', sa.String(length=45), nullable=False))
    op.add_column('cameras', sa.Column('port', sa.Integer(), nullable=False))
    op.add_column('cameras', sa.Column('path', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('cameras_rtsp_url_key'), 'cameras', type_='unique')
    op.drop_column('cameras', 'rtsp_url')
    op.drop_column('cameras', 'latitude')
    op.drop_column('cameras', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('cameras', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('cameras', sa.Column('rtsp_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('cameras_rtsp_url_key'), 'cameras', ['rtsp_url'], postgresql_nulls_not_distinct=False)
    op.drop_column('cameras', 'path')
    op.drop_column('cameras', 'port')
    op.drop_column('cameras', 'ip_address')
    # ### end Alembic commands ###
