"""update_frame_rate_to_60fps

Revision ID: 6f66e43a6c94
Revises: 563bbcfd5bd0
Create Date: 2025-08-15 19:45:19.525602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f66e43a6c94'
down_revision = '563bbcfd5bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
